-- Create warehouse
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE DATASTAGE_WH
WITH 
WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 2 
SCALING_POLICY = 'ECONOMY' 
COMMENT = 'Warehouse for DataStage';

-- Create Role
USE ROLE USERADMIN;

CREATE OR REPLACE ROLE "DATASTAGE_ROLE";

-- Create User
CREATE OR REPLACE USER DATASTAGE_USER PASSWORD = 'datastageuser' 
	MUST_CHANGE_PASSWORD = FALSE
	DEFAULT_WAREHOUSE = DATASTAGE_WH 
	DEFAULT_ROLE = DATASTAGE_ROLE;

--GRANT all required access
USE ROLE SECURITYADMIN;

--GRANT role to the user
GRANT ROLE "DATASTAGE_ROLE" TO ROLE "SYSADMIN";
GRANT ROLE "DATASTAGE_ROLE" TO USER "DATASTAGE_USER";

--GRANT warehouse usage access to role
GRANT USAGE ON WAREHOUSE DATASTAGE_WH TO ROLE DATASTAGE_ROLE;

GRANT USAGE ON WAREHOUSE DATASTAGE_WH TO ROLE DATASTAGE_ROLE;
  
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE DATASTAGE_ROLE;

-- Validate Access
SHOW GRANTS TO USER DATASTAGE_USER;